### ISSUE TITLE
[FEATURE REQUEST] Time duration between check should be configurable down to seconds.

### ISSUE THREAD

**Issue by hossain-khan** [hossain-khan/android-keep-alive#68]
Some request came to check for seconds based to ensure selected app always runs.

**Comment by hossain-khan** [comment]
Checkout `android-keep-alive-seconds.apk` from:
* https://file.io/9rLDRzKYOXYg
* https://fromsmash.com/Keep-Alive-Seconds

**Comment by ALXCONNECT** [comment]
link is expired. Can you post this again?
What OS is this compatible with, because it does not work in Android 11 (does not re-launch app that I exited on purpose. I accepted all 3 permissions). Also in Android 7, it says parsing error when trying to install.
Thank you.

**Comment by hossain-khan** [comment]
The min app version is [Android 9](https://developer.android.com/about/versions/pie)

https://github.com/hossain-khan/android-keep-alive/blob/d3f37dfdbabf6106b175e6051858f6bd7ce533ef/app/build.gradle.kts#L16

This build was very specific ask, doing check every second to every 60 seconds. Which is not very good thing to do on any phone. Are you sure you want this build?

**Comment by ALXCONNECT** [comment]
Yes please. 
This is being tested on an android box, so i am not worried about the battery.

Is this app use a lot of ram or resources? (used on 2gb vs 4gb device).

How can i test to see if it is actually working? I am using your app along side an app that has a autoboot feature.

Thanks again.

**Comment by hossain-khan** [comment]
@ALXCONNECT I added the APK in the release, it should be available all the time.

https://github.com/hossain-khan/android-keep-alive/releases/tag/v1.9-seconds

**Comment by hossain-khan** [comment]
> Is this app use a lot of ram or resources? (used on 2gb vs 4gb device).

I mainly made this app to run on Pixel 1 device which is 9 year old phone with 4GB ram, that's where my immortal apps gets killed all the time. I think it should work fine on 4GB device, not sure about 2GB.



> How can i test to see if it is actually working? I am using your app along side an app that has a autoboot feature.

I added remote logging feature just for this, as I wanted to check if the app is working over period of 1-2 days.

However, doing fast checks may not be ideal for remote logging, also setting it up requires technical knowledge unfortunately. Feel free to take a look at the doc - https://github.com/hossain-khan/android-keep-alive/blob/main/REMOTE-MONITORING.md
